# Generated by Django 5.0.6 on 2025-03-13 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_map_delete_location'),
        ('warehouse', '0017_lease_blockchain_tx_warehouse_blockchain_tx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_location', to='warehouse.warehouse'),
        ),
    ]
