# Generated by Django 5.0.6 on 2024-07-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('lessor', 'Lessor'), ('tenant', 'Tenant')], max_length=6),
        ),
    ]
