# Generated by Django 5.0.6 on 2024-07-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessor',
            fields=[
                ('lessor_id', models.AutoField(primary_key=True, serialize=False)),
                ('lessor_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='lessor_photos/')),
            ],
        ),
    ]
