# Generated by Django 5.0.6 on 2024-07-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_lessor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('resend_attempts', models.IntegerField(default=0)),
                ('last_resend_time', models.DateTimeField(blank=True, null=True)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
    ]
