# Generated by Django 5.0.6 on 2024-07-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_unverifieduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessor',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to='lessor_id/'),
        ),
    ]
