# Generated by Django 5.0.6 on 2025-03-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_tenant_latitude_tenant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessor',
            name='wallet_address',
            field=models.CharField(default='0x5835601ec240807926F67be24f8C966A9338c599', max_length=42),
        ),
        migrations.AddField(
            model_name='tenant',
            name='wallet_address',
            field=models.CharField(default='0x5835601ec240807926F67be24f8C966A9338c599', max_length=42),
        ),
    ]
