# Generated by Django 5.0.6 on 2025-01-16 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0014_alter_warehousereview_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('item_length', models.FloatField(help_text='Length of the item in meters.')),
                ('item_width', models.FloatField(help_text='Width of the item in meters.')),
                ('item_height', models.FloatField(help_text='Height of the item in meters.')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_length', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_breadth', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('used_height', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('RECEIVING', 'Receiving Area'), ('STORAGE', 'Storage Area'), ('PICKING', 'Picking Area')], max_length=20)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length of the zone in meters.', max_digits=10)),
                ('breadth', models.DecimalField(decimal_places=2, help_text='Breadth of the zone in meters.', max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height of the zone in meters.', max_digits=10)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.FloatField(help_text='Length of the storage space in meters.')),
                ('width', models.FloatField(help_text='Width of the storage space in meters.')),
                ('height', models.FloatField(help_text='Height of the storage space in meters.')),
                ('stackable', models.BooleanField(default=False, help_text='Whether the item can be stacked.')),
                ('max_stacking_height', models.FloatField(help_text='Maximum number of stacking layers allowed based on the item height.')),
                ('aisle_width', models.FloatField(help_text='Width of the aisles between storage units.')),
                ('item_count', models.PositiveIntegerField(default=0, help_text='Number of items in this location.')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.zone')),
            ],
        ),
    ]
