# Generated by Django 5.0.6 on 2025-02-05 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_zone_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylocation',
            name='aisle_width',
        ),
    ]
