# Generated by Django 5.0.6 on 2025-02-05 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventorylocation_aisle_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylocation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.zone'),
        ),
    ]
