# Generated by Django 5.0.6 on 2025-02-19 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorylocation_zone'),
        ('warehouse', '0016_warehouse_last_activity_warehouse_popularity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='warehouse.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('name', 'warehouse')},
        ),
    ]
