# Generated by Django 5.0.6 on 2025-03-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_warehouse_and_more'),
        ('warehouse', '0018_warehouseavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehouse.warehouse'),
        ),
    ]
