# Generated by Django 5.0.7 on 2024-08-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_warehouse_photo_warehousephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
