# Generated by Django 5.0.7 on 2024-08-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehouse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='ownership_documents',
            field=models.FileField(blank=True, null=True, upload_to='ownership_docs/'),
        ),
    ]
