# Generated by Django 5.0.6 on 2024-08-21 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_message_is_read'),
        ('warehouse', '0004_alter_warehouse_ownership_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('lease_id', models.AutoField(primary_key=True, serialize=False)),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
    ]
