# Generated by Django 5.0.6 on 2024-08-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_remove_lease_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
