# Generated by Django 5.0.6 on 2024-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_warehouse_breadth_warehouse_height_warehouse_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
