# Generated by Django 5.0.6 on 2025-02-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_alter_warehouse_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
