# Generated by Django 5.0.6 on 2025-03-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_warehouse_last_activity_warehouse_popularity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=66),
        ),
    ]
