# Generated by Django 5.0.6 on 2025-03-13 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_lessor_wallet_address_tenant_wallet_address'),
        ('warehouse', '0017_lease_blockchain_tx_warehouse_blockchain_tx'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=20)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.lessor')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='warehouse.warehouse')),
            ],
        ),
    ]
